xlsx parser
Muhamob/SBT-catch-the-spy pull request #2
Opened 2020-03-13 09:08 UTC by Muhamob

2020-03-14 22:05 UTC, sergeynikiforov761 requested changes

2020-03-14 22:05 UTC, sergeynikiforov761 commented on src/parsers/xlsx.py
> +class SheetParser:
Поправь, если нужно тут (поменяли бэйзлайн)

2020-03-15 19:24 UTC, Muhamob commented
Исправил

2020-03-15 19:25 UTC, Muhamob commented
Правда не очень понял как с эти ребэйзом делать, но в итоге вроде получилось

2020-03-16 20:14 UTC, sergeynikiforov761 approved these changes

2020-03-16 20:14 UTC, merged